/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Model;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-30T20:12:45.563455115-05:00[America/Chicago]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "models", description = "the models API")
public interface ModelsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /models : gets model.
     * Gets the model with the specified name.
     *
     * @param name The name of the model to retrieve. (required)
     * @return A JSON array of model names (status code 200)
     *         or Bad Request - The request was invalid or cannot be served. (status code 400)
     */
    @Operation(
        operationId = "modelsGet",
        summary = "gets model.",
        description = "Gets the model with the specified name.",
        responses = {
            @ApiResponse(responseCode = "200", description = "A JSON array of model names", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Model.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request - The request was invalid or cannot be served.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/models",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Model> modelsGet(
        @NotNull @Parameter(name = "name", description = "The name of the model to retrieve.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = true) String name
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"subAudit\" : [ { \"courses\" : [ \"courses\", \"courses\" ], \"name\" : \"name\", \"cardinality\" : \"cardinality\" }, { \"courses\" : [ \"courses\", \"courses\" ], \"name\" : \"name\", \"cardinality\" : \"cardinality\" } ], \"info\" : { \"code\" : \"code\", \"program\" : \"program\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /models : submits a new model.
     * Creates a new model with the specified name and subAudit.
     *
     * @param model  (required)
     * @return Model created successfully (status code 201)
     *         or Bad Request - The request was invalid or cannot be served. (status code 400)
     */
    @Operation(
        operationId = "modelsPost",
        summary = "submits a new model.",
        description = "Creates a new model with the specified name and subAudit.",
        responses = {
            @ApiResponse(responseCode = "201", description = "Model created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Model.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request - The request was invalid or cannot be served.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/models",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Model> modelsPost(
        @Parameter(name = "Model", description = "", required = true) @Valid @RequestBody Model model
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"subAudit\" : [ { \"courses\" : [ \"courses\", \"courses\" ], \"name\" : \"name\", \"cardinality\" : \"cardinality\" }, { \"courses\" : [ \"courses\", \"courses\" ], \"name\" : \"name\", \"cardinality\" : \"cardinality\" } ], \"info\" : { \"code\" : \"code\", \"program\" : \"program\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
